/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$splat'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTeachersRouteImport } from './routes/demo/teachers'
import { Route as DemoStudentsRouteImport } from './routes/demo/students'
import { Route as DemoSettingsRouteImport } from './routes/demo/settings'
import { Route as DemoSchoolsRouteImport } from './routes/demo/schools'
import { Route as DemoReportsRouteImport } from './routes/demo/reports'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DemoClassroomRouteImport } from './routes/demo/classroom'
import { Route as DemoClassesRouteImport } from './routes/demo/classes'
import { Route as DemoAttendanceRouteImport } from './routes/demo/attendance'
import { Route as mainSettingsRouteImport } from './routes/(main)/settings'
import { Route as mainProfileRouteImport } from './routes/(main)/profile'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainLessonsIndexRouteImport } from './routes/(main)/lessons.index'
import { Route as mainLessonsEuRouteImport } from './routes/(main)/lessons.eu'
import { Route as mainLessonsAdvancedRouteImport } from './routes/(main)/lessons.advanced'
import { Route as LessonsEverybodyUp0Unit1Lesson3IndexRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-3/index'
import { Route as LessonsEverybodyUp0Unit1Lesson2IndexRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-2/index'
import { Route as LessonsEverybodyUp0Unit1Lesson1IndexRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/index'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/index'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/index'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/index'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/index'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/index'
import { Route as LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson3PresentationLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson3FlashcardsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
import { Route as LessonsEverybodyUp0Unit1Lesson3ExercisesRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-3/exercises'
import { Route as LessonsEverybodyUp0Unit1Lesson3AssignmentsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-3/assignments'
import { Route as LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson2PresentationLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson2FlashcardsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
import { Route as LessonsEverybodyUp0Unit1Lesson2AssignmentsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-2/assignments'
import { Route as LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson1PresentationLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson1FlashcardsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
import { Route as LessonsEverybodyUp0Unit1Lesson1AssignmentsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/assignments'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'

const SplatRoute = SplatRouteImport.update({
  id: '/$splat',
  path: '/$splat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTeachersRoute = DemoTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoStudentsRoute = DemoStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSchoolsRoute = DemoSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoReportsRoute = DemoReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoClassroomRoute = DemoClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoClassesRoute = DemoClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoAttendanceRoute = DemoAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DemoRouteRoute,
} as any)
const mainSettingsRoute = mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainProfileRoute = mainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const mainLessonsIndexRoute = mainLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLessonsEuRoute = mainLessonsEuRouteImport.update({
  id: '/lessons/eu',
  path: '/lessons/eu',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLessonsAdvancedRoute = mainLessonsAdvancedRouteImport.update({
  id: '/lessons/advanced',
  path: '/lessons/advanced',
  getParentRoute: () => mainRouteRoute,
} as any)
const LessonsEverybodyUp0Unit1Lesson3IndexRoute =
  LessonsEverybodyUp0Unit1Lesson3IndexRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-3/',
    path: '/lessons/everybody-up-0/unit-1/lesson-3/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson2IndexRoute =
  LessonsEverybodyUp0Unit1Lesson2IndexRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-2/',
    path: '/lessons/everybody-up-0/unit-1/lesson-2/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1IndexRoute =
  LessonsEverybodyUp0Unit1Lesson1IndexRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute =
  LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute =
  LessonsEverybodyUp0Unit1Lesson3PresentationLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute =
  LessonsEverybodyUp0Unit1Lesson3FlashcardsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-3/flashcards',
    path: '/lessons/everybody-up-0/unit-1/lesson-3/flashcards',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson3ExercisesRoute =
  LessonsEverybodyUp0Unit1Lesson3ExercisesRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-3/exercises',
    path: '/lessons/everybody-up-0/unit-1/lesson-3/exercises',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute =
  LessonsEverybodyUp0Unit1Lesson3AssignmentsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-3/assignments',
    path: '/lessons/everybody-up-0/unit-1/lesson-3/assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute =
  LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute =
  LessonsEverybodyUp0Unit1Lesson2PresentationLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute =
  LessonsEverybodyUp0Unit1Lesson2FlashcardsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-2/flashcards',
    path: '/lessons/everybody-up-0/unit-1/lesson-2/flashcards',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute =
  LessonsEverybodyUp0Unit1Lesson2AssignmentsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-2/assignments',
    path: '/lessons/everybody-up-0/unit-1/lesson-2/assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute =
  LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute =
  LessonsEverybodyUp0Unit1Lesson1PresentationLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute =
  LessonsEverybodyUp0Unit1Lesson1FlashcardsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute =
  LessonsEverybodyUp0Unit1Lesson1AssignmentsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/assignments',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/assignments',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof mainRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof mainProfileRoute
  '/settings': typeof mainSettingsRoute
  '/demo/attendance': typeof DemoAttendanceRoute
  '/demo/classes': typeof DemoClassesRoute
  '/demo/classroom': typeof DemoClassroomRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/reports': typeof DemoReportsRoute
  '/demo/schools': typeof DemoSchoolsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/students': typeof DemoStudentsRoute
  '/demo/teachers': typeof DemoTeachersRoute
  '/lessons/advanced': typeof mainLessonsAdvancedRoute
  '/lessons/eu': typeof mainLessonsEuRoute
  '/lessons': typeof mainLessonsIndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/assignments': typeof LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/assignments': typeof LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/flashcards': typeof LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/assignments': typeof LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/exercises': typeof LessonsEverybodyUp0Unit1Lesson3ExercisesRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/flashcards': typeof LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-1': typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-2': typeof LessonsEverybodyUp0Unit1Lesson2IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-3': typeof LessonsEverybodyUp0Unit1Lesson3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof mainProfileRoute
  '/settings': typeof mainSettingsRoute
  '/demo/attendance': typeof DemoAttendanceRoute
  '/demo/classes': typeof DemoClassesRoute
  '/demo/classroom': typeof DemoClassroomRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/reports': typeof DemoReportsRoute
  '/demo/schools': typeof DemoSchoolsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/students': typeof DemoStudentsRoute
  '/demo/teachers': typeof DemoTeachersRoute
  '/lessons/advanced': typeof mainLessonsAdvancedRoute
  '/lessons/eu': typeof mainLessonsEuRoute
  '/lessons': typeof mainLessonsIndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/assignments': typeof LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/assignments': typeof LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/flashcards': typeof LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/assignments': typeof LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/exercises': typeof LessonsEverybodyUp0Unit1Lesson3ExercisesRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/flashcards': typeof LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-1': typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-2': typeof LessonsEverybodyUp0Unit1Lesson2IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-3': typeof LessonsEverybodyUp0Unit1Lesson3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/demo': typeof DemoRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(main)/profile': typeof mainProfileRoute
  '/(main)/settings': typeof mainSettingsRoute
  '/demo/attendance': typeof DemoAttendanceRoute
  '/demo/classes': typeof DemoClassesRoute
  '/demo/classroom': typeof DemoClassroomRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/reports': typeof DemoReportsRoute
  '/demo/schools': typeof DemoSchoolsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/students': typeof DemoStudentsRoute
  '/demo/teachers': typeof DemoTeachersRoute
  '/(main)/lessons/advanced': typeof mainLessonsAdvancedRoute
  '/(main)/lessons/eu': typeof mainLessonsEuRoute
  '/(main)/lessons/': typeof mainLessonsIndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/assignments': typeof LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/assignments': typeof LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/flashcards': typeof LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/assignments': typeof LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/exercises': typeof LessonsEverybodyUp0Unit1Lesson3ExercisesRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/flashcards': typeof LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/': typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-2/': typeof LessonsEverybodyUp0Unit1Lesson2IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-3/': typeof LessonsEverybodyUp0Unit1Lesson3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/$splat'
    | '/login'
    | '/signup'
    | '/profile'
    | '/settings'
    | '/demo/attendance'
    | '/demo/classes'
    | '/demo/classroom'
    | '/demo/dashboard'
    | '/demo/reports'
    | '/demo/schools'
    | '/demo/settings'
    | '/demo/students'
    | '/demo/teachers'
    | '/lessons/advanced'
    | '/lessons/eu'
    | '/lessons'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-2/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-3/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-3/exercises'
    | '/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5'
    | '/lessons/everybody-up-0/unit-1/lesson-1'
    | '/lessons/everybody-up-0/unit-1/lesson-2'
    | '/lessons/everybody-up-0/unit-1/lesson-3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/$splat'
    | '/login'
    | '/signup'
    | '/profile'
    | '/settings'
    | '/demo/attendance'
    | '/demo/classes'
    | '/demo/classroom'
    | '/demo/dashboard'
    | '/demo/reports'
    | '/demo/schools'
    | '/demo/settings'
    | '/demo/students'
    | '/demo/teachers'
    | '/lessons/advanced'
    | '/lessons/eu'
    | '/lessons'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-2/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-3/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-3/exercises'
    | '/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5'
    | '/lessons/everybody-up-0/unit-1/lesson-1'
    | '/lessons/everybody-up-0/unit-1/lesson-2'
    | '/lessons/everybody-up-0/unit-1/lesson-3'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/demo'
    | '/$splat'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(main)/profile'
    | '/(main)/settings'
    | '/demo/attendance'
    | '/demo/classes'
    | '/demo/classroom'
    | '/demo/dashboard'
    | '/demo/reports'
    | '/demo/schools'
    | '/demo/settings'
    | '/demo/students'
    | '/demo/teachers'
    | '/(main)/lessons/advanced'
    | '/(main)/lessons/eu'
    | '/(main)/lessons/'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-2/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-3/assignments'
    | '/lessons/everybody-up-0/unit-1/lesson-3/exercises'
    | '/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/'
    | '/lessons/everybody-up-0/unit-1/lesson-1/'
    | '/lessons/everybody-up-0/unit-1/lesson-2/'
    | '/lessons/everybody-up-0/unit-1/lesson-3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute
  LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute: typeof LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute
  LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute: typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute: typeof LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute
  LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute: typeof LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute
  LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute
  LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute
  LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute: typeof LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute
  LessonsEverybodyUp0Unit1Lesson3ExercisesRoute: typeof LessonsEverybodyUp0Unit1Lesson3ExercisesRoute
  LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute: typeof LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute
  LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute
  LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute
  LessonsEverybodyUp0Unit1Lesson1IndexRoute: typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
  LessonsEverybodyUp0Unit1Lesson2IndexRoute: typeof LessonsEverybodyUp0Unit1Lesson2IndexRoute
  LessonsEverybodyUp0Unit1Lesson3IndexRoute: typeof LessonsEverybodyUp0Unit1Lesson3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$splat': {
      id: '/$splat'
      path: '/$splat'
      fullPath: '/$splat'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/teachers': {
      id: '/demo/teachers'
      path: '/teachers'
      fullPath: '/demo/teachers'
      preLoaderRoute: typeof DemoTeachersRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/students': {
      id: '/demo/students'
      path: '/students'
      fullPath: '/demo/students'
      preLoaderRoute: typeof DemoStudentsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/schools': {
      id: '/demo/schools'
      path: '/schools'
      fullPath: '/demo/schools'
      preLoaderRoute: typeof DemoSchoolsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/reports': {
      id: '/demo/reports'
      path: '/reports'
      fullPath: '/demo/reports'
      preLoaderRoute: typeof DemoReportsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/classroom': {
      id: '/demo/classroom'
      path: '/classroom'
      fullPath: '/demo/classroom'
      preLoaderRoute: typeof DemoClassroomRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/classes': {
      id: '/demo/classes'
      path: '/classes'
      fullPath: '/demo/classes'
      preLoaderRoute: typeof DemoClassesRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/attendance': {
      id: '/demo/attendance'
      path: '/attendance'
      fullPath: '/demo/attendance'
      preLoaderRoute: typeof DemoAttendanceRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/(main)/settings': {
      id: '/(main)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/profile': {
      id: '/(main)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainProfileRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/lessons/': {
      id: '/(main)/lessons/'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof mainLessonsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/lessons/eu': {
      id: '/(main)/lessons/eu'
      path: '/lessons/eu'
      fullPath: '/lessons/eu'
      preLoaderRoute: typeof mainLessonsEuRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/lessons/advanced': {
      id: '/(main)/lessons/advanced'
      path: '/lessons/advanced'
      fullPath: '/lessons/advanced'
      preLoaderRoute: typeof mainLessonsAdvancedRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/lessons/everybody-up-0/unit-1/lesson-3/': {
      id: '/lessons/everybody-up-0/unit-1/lesson-3/'
      path: '/lessons/everybody-up-0/unit-1/lesson-3'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-3'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-2/': {
      id: '/lessons/everybody-up-0/unit-1/lesson-2/'
      path: '/lessons/everybody-up-0/unit-1/lesson-2'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-2'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/'
      path: '/lessons/everybody-up-0/unit-1/lesson-1'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-3/youtube-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-3/presentation-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson3PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-3/flashcards': {
      id: '/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
      path: '/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-3/flashcards'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson3FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-3/exercises': {
      id: '/lessons/everybody-up-0/unit-1/lesson-3/exercises'
      path: '/lessons/everybody-up-0/unit-1/lesson-3/exercises'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-3/exercises'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson3ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-3/assignments': {
      id: '/lessons/everybody-up-0/unit-1/lesson-3/assignments'
      path: '/lessons/everybody-up-0/unit-1/lesson-3/assignments'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-3/assignments'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson3AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-2/youtube-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-2/presentation-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson2PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-2/flashcards': {
      id: '/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
      path: '/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-2/flashcards'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson2FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-2/assignments': {
      id: '/lessons/everybody-up-0/unit-1/lesson-2/assignments'
      path: '/lessons/everybody-up-0/unit-1/lesson-2/assignments'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-2/assignments'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson2AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/assignments': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/assignments'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/assignments'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/assignments'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/youtube-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/presentation-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/flashcards'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/exercises'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-5/assignments'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/youtube-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/presentation-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/flashcards'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/exercises'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-4/assignments'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/youtube-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/presentation-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/flashcards'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-3/assignments'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/youtube-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/presentation-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/flashcards'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-2/assignments'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/assignments'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainProfileRoute: typeof mainProfileRoute
  mainSettingsRoute: typeof mainSettingsRoute
  mainLessonsAdvancedRoute: typeof mainLessonsAdvancedRoute
  mainLessonsEuRoute: typeof mainLessonsEuRoute
  mainLessonsIndexRoute: typeof mainLessonsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainProfileRoute: mainProfileRoute,
  mainSettingsRoute: mainSettingsRoute,
  mainLessonsAdvancedRoute: mainLessonsAdvancedRoute,
  mainLessonsEuRoute: mainLessonsEuRoute,
  mainLessonsIndexRoute: mainLessonsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface DemoRouteRouteChildren {
  DemoAttendanceRoute: typeof DemoAttendanceRoute
  DemoClassesRoute: typeof DemoClassesRoute
  DemoClassroomRoute: typeof DemoClassroomRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoReportsRoute: typeof DemoReportsRoute
  DemoSchoolsRoute: typeof DemoSchoolsRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoStudentsRoute: typeof DemoStudentsRoute
  DemoTeachersRoute: typeof DemoTeachersRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoAttendanceRoute: DemoAttendanceRoute,
  DemoClassesRoute: DemoClassesRoute,
  DemoClassroomRoute: DemoClassroomRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoReportsRoute: DemoReportsRoute,
  DemoSchoolsRoute: DemoSchoolsRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoStudentsRoute: DemoStudentsRoute,
  DemoTeachersRoute: DemoTeachersRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1AssignmentsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2AssignmentsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2FlashcardsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2PresentationLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2YoutubeLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3AssignmentsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3FlashcardsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3PresentationLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3YoutubeLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4AssignmentsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4ExercisesRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4FlashcardsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4PresentationLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4YoutubeLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5AssignmentsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5ExercisesRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5FlashcardsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5PresentationLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5YoutubeLessonRoute,
  LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute:
    LessonsEverybodyUp0Unit1Lesson1AssignmentsRoute,
  LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute:
    LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute,
  LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute:
    LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute,
  LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute:
    LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute,
  LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute:
    LessonsEverybodyUp0Unit1Lesson2AssignmentsRoute,
  LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute:
    LessonsEverybodyUp0Unit1Lesson2FlashcardsRoute,
  LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute:
    LessonsEverybodyUp0Unit1Lesson2PresentationLessonRoute,
  LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute:
    LessonsEverybodyUp0Unit1Lesson2YoutubeLessonRoute,
  LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute:
    LessonsEverybodyUp0Unit1Lesson3AssignmentsRoute,
  LessonsEverybodyUp0Unit1Lesson3ExercisesRoute:
    LessonsEverybodyUp0Unit1Lesson3ExercisesRoute,
  LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute:
    LessonsEverybodyUp0Unit1Lesson3FlashcardsRoute,
  LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute:
    LessonsEverybodyUp0Unit1Lesson3PresentationLessonRoute,
  LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute:
    LessonsEverybodyUp0Unit1Lesson3YoutubeLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson2IndexRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson3IndexRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson4IndexRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson5IndexRoute,
  LessonsEverybodyUp0Unit1Lesson1IndexRoute:
    LessonsEverybodyUp0Unit1Lesson1IndexRoute,
  LessonsEverybodyUp0Unit1Lesson2IndexRoute:
    LessonsEverybodyUp0Unit1Lesson2IndexRoute,
  LessonsEverybodyUp0Unit1Lesson3IndexRoute:
    LessonsEverybodyUp0Unit1Lesson3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
