/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$splat'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as mainSettingsRouteImport } from './routes/(main)/settings'
import { Route as mainProfileRouteImport } from './routes/(main)/profile'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as LessonsEverybodyUp0Unit1Lesson1IndexRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/index'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/index'
import { Route as LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson1PresentationLessonRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
import { Route as LessonsEverybodyUp0Unit1Lesson1HomeworkRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/homework'
import { Route as LessonsEverybodyUp0Unit1Lesson1FlashcardsRouteImport } from './routes/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
import { Route as LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRouteImport } from './routes/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'

const SplatRoute = SplatRouteImport.update({
  id: '/$splat',
  path: '/$splat',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainSettingsRoute = mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainProfileRoute = mainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const LessonsEverybodyUp0Unit1Lesson1IndexRoute =
  LessonsEverybodyUp0Unit1Lesson1IndexRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute =
  LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute =
  LessonsEverybodyUp0Unit1Lesson1PresentationLessonRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1HomeworkRoute =
  LessonsEverybodyUp0Unit1Lesson1HomeworkRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/homework',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/homework',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute =
  LessonsEverybodyUp0Unit1Lesson1FlashcardsRouteImport.update({
    id: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards',
    path: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute =
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRouteImport.update(
    {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards',
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof mainRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof mainProfileRoute
  '/settings': typeof mainSettingsRoute
  '/lessons': typeof LessonsIndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/homework': typeof LessonsEverybodyUp0Unit1Lesson1HomeworkRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-1': typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof mainProfileRoute
  '/settings': typeof mainSettingsRoute
  '/lessons': typeof LessonsIndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/homework': typeof LessonsEverybodyUp0Unit1Lesson1HomeworkRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-1': typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(main)/profile': typeof mainProfileRoute
  '/(main)/settings': typeof mainSettingsRoute
  '/lessons/': typeof LessonsIndexRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/homework': typeof LessonsEverybodyUp0Unit1Lesson1HomeworkRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/': typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  '/lessons/everybody-up-0/unit-1/lesson-1/': typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$splat'
    | '/login'
    | '/signup'
    | '/profile'
    | '/settings'
    | '/lessons'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-1/homework'
    | '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
    | '/lessons/everybody-up-0/unit-1/lesson-1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$splat'
    | '/login'
    | '/signup'
    | '/profile'
    | '/settings'
    | '/lessons'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-1/homework'
    | '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
    | '/lessons/everybody-up-0/unit-1/lesson-1'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/$splat'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(main)/profile'
    | '/(main)/settings'
    | '/lessons/'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
    | '/lessons/everybody-up-0/unit-1/lesson-1/homework'
    | '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
    | '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
    | '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/'
    | '/lessons/everybody-up-0/unit-1/lesson-1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute
  LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute: typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute
  LessonsEverybodyUp0Unit1Lesson1HomeworkRoute: typeof LessonsEverybodyUp0Unit1Lesson1HomeworkRoute
  LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute
  LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute: typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute
  LessonsEverybodyUp0Unit1Lesson1IndexRoute: typeof LessonsEverybodyUp0Unit1Lesson1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$splat': {
      id: '/$splat'
      path: '/$splat'
      fullPath: '/$splat'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/settings': {
      id: '/(main)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/profile': {
      id: '/(main)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainProfileRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/'
      path: '/lessons/everybody-up-0/unit-1/lesson-1'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/youtube-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/presentation-lesson'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/homework': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/homework'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/homework'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/homework'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/everybody-up-0/unit-1/lesson-1/flashcards': {
      id: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
      path: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
      fullPath: '/lessons/everybody-up-0/unit-1/lesson-1/flashcards'
      preLoaderRoute: typeof LessonsEverybodyUp0Unit1Lesson1FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/youtube-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/presentation-lesson'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/homework'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards': {
      id: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
      path: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
      fullPath: '/lessons/advanced-topics/multiple-intelligence-theory/lesson-1/flashcards'
      preLoaderRoute: typeof LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainProfileRoute: typeof mainProfileRoute
  mainSettingsRoute: typeof mainSettingsRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainProfileRoute: mainProfileRoute,
  mainSettingsRoute: mainSettingsRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1FlashcardsRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1HomeworkRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1PresentationLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1YoutubeLessonRoute,
  LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute:
    LessonsEverybodyUp0Unit1Lesson1FlashcardsRoute,
  LessonsEverybodyUp0Unit1Lesson1HomeworkRoute:
    LessonsEverybodyUp0Unit1Lesson1HomeworkRoute,
  LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute:
    LessonsEverybodyUp0Unit1Lesson1PresentationLessonRoute,
  LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute:
    LessonsEverybodyUp0Unit1Lesson1YoutubeLessonRoute,
  LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute:
    LessonsAdvancedTopicsMultipleIntelligenceTheoryLesson1IndexRoute,
  LessonsEverybodyUp0Unit1Lesson1IndexRoute:
    LessonsEverybodyUp0Unit1Lesson1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
