/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$splat'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainteacherRouteRouteImport } from './routes/(main)/(teacher)/route'
import { Route as mainLessonsIndexRouteImport } from './routes/(main)/lessons/index'
import { Route as mainLessonsSplatRouteImport } from './routes/(main)/lessons/$'
import { Route as mainteacherTeachersRouteImport } from './routes/(main)/(teacher)/teachers'
import { Route as mainteacherStudentsRouteImport } from './routes/(main)/(teacher)/students'
import { Route as mainteacherSchoolsRouteImport } from './routes/(main)/(teacher)/schools'
import { Route as mainteacherReportsRouteImport } from './routes/(main)/(teacher)/reports'
import { Route as mainteacherClassroomRouteImport } from './routes/(main)/(teacher)/classroom'
import { Route as mainteacherClassesRouteImport } from './routes/(main)/(teacher)/classes'
import { Route as mainteacherAttendanceRouteImport } from './routes/(main)/(teacher)/attendance'
import { Route as maincommonSettingsRouteImport } from './routes/(main)/(common)/settings'
import { Route as maincommonProfileRouteImport } from './routes/(main)/(common)/profile'
import { Route as maincommonDashboardRouteImport } from './routes/(main)/(common)/dashboard'
import { Route as mainLessonsCourseUnitLessonRouteRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/route'
import { Route as mainLessonsCourseUnitLessonIndexRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/index'
import { Route as mainLessonsCourseUnitLessonActivityRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/$activity'
import { Route as mainLessonsCourseUnitLessonYoutubeIdRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/youtube.$id'
import { Route as mainLessonsCourseUnitLessonPagesIdRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/pages.$id'
import { Route as mainLessonsCourseUnitLessonGoogleslideIdRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/googleslide.$id'
import { Route as mainLessonsCourseUnitLessonEmbedIdRouteImport } from './routes/(main)/lessons/$course.$unit.$lesson/embed.$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$splat',
  path: '/$splat',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const mainteacherRouteRoute = mainteacherRouteRouteImport.update({
  id: '/(teacher)',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLessonsIndexRoute = mainLessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLessonsSplatRoute = mainLessonsSplatRouteImport.update({
  id: '/lessons/$',
  path: '/lessons/$',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainteacherTeachersRoute = mainteacherTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const mainteacherStudentsRoute = mainteacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const mainteacherSchoolsRoute = mainteacherSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const mainteacherReportsRoute = mainteacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const mainteacherClassroomRoute = mainteacherClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const mainteacherClassesRoute = mainteacherClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const mainteacherAttendanceRoute = mainteacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => mainteacherRouteRoute,
} as any)
const maincommonSettingsRoute = maincommonSettingsRouteImport.update({
  id: '/(common)/settings',
  path: '/settings',
  getParentRoute: () => mainRouteRoute,
} as any)
const maincommonProfileRoute = maincommonProfileRouteImport.update({
  id: '/(common)/profile',
  path: '/profile',
  getParentRoute: () => mainRouteRoute,
} as any)
const maincommonDashboardRoute = maincommonDashboardRouteImport.update({
  id: '/(common)/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainLessonsCourseUnitLessonRouteRoute =
  mainLessonsCourseUnitLessonRouteRouteImport.update({
    id: '/lessons/$course/$unit/$lesson',
    path: '/lessons/$course/$unit/$lesson',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainLessonsCourseUnitLessonIndexRoute =
  mainLessonsCourseUnitLessonIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainLessonsCourseUnitLessonRouteRoute,
  } as any)
const mainLessonsCourseUnitLessonActivityRoute =
  mainLessonsCourseUnitLessonActivityRouteImport.update({
    id: '/$activity',
    path: '/$activity',
    getParentRoute: () => mainLessonsCourseUnitLessonRouteRoute,
  } as any)
const mainLessonsCourseUnitLessonYoutubeIdRoute =
  mainLessonsCourseUnitLessonYoutubeIdRouteImport.update({
    id: '/youtube/$id',
    path: '/youtube/$id',
    getParentRoute: () => mainLessonsCourseUnitLessonRouteRoute,
  } as any)
const mainLessonsCourseUnitLessonPagesIdRoute =
  mainLessonsCourseUnitLessonPagesIdRouteImport.update({
    id: '/pages/$id',
    path: '/pages/$id',
    getParentRoute: () => mainLessonsCourseUnitLessonRouteRoute,
  } as any)
const mainLessonsCourseUnitLessonGoogleslideIdRoute =
  mainLessonsCourseUnitLessonGoogleslideIdRouteImport.update({
    id: '/googleslide/$id',
    path: '/googleslide/$id',
    getParentRoute: () => mainLessonsCourseUnitLessonRouteRoute,
  } as any)
const mainLessonsCourseUnitLessonEmbedIdRoute =
  mainLessonsCourseUnitLessonEmbedIdRouteImport.update({
    id: '/embed/$id',
    path: '/embed/$id',
    getParentRoute: () => mainLessonsCourseUnitLessonRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof mainteacherRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof maincommonDashboardRoute
  '/profile': typeof maincommonProfileRoute
  '/settings': typeof maincommonSettingsRoute
  '/attendance': typeof mainteacherAttendanceRoute
  '/classes': typeof mainteacherClassesRoute
  '/classroom': typeof mainteacherClassroomRoute
  '/reports': typeof mainteacherReportsRoute
  '/schools': typeof mainteacherSchoolsRoute
  '/students': typeof mainteacherStudentsRoute
  '/teachers': typeof mainteacherTeachersRoute
  '/lessons/$': typeof mainLessonsSplatRoute
  '/lessons': typeof mainLessonsIndexRoute
  '/lessons/$course/$unit/$lesson': typeof mainLessonsCourseUnitLessonRouteRouteWithChildren
  '/lessons/$course/$unit/$lesson/$activity': typeof mainLessonsCourseUnitLessonActivityRoute
  '/lessons/$course/$unit/$lesson/': typeof mainLessonsCourseUnitLessonIndexRoute
  '/lessons/$course/$unit/$lesson/embed/$id': typeof mainLessonsCourseUnitLessonEmbedIdRoute
  '/lessons/$course/$unit/$lesson/googleslide/$id': typeof mainLessonsCourseUnitLessonGoogleslideIdRoute
  '/lessons/$course/$unit/$lesson/pages/$id': typeof mainLessonsCourseUnitLessonPagesIdRoute
  '/lessons/$course/$unit/$lesson/youtube/$id': typeof mainLessonsCourseUnitLessonYoutubeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof mainteacherRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof maincommonDashboardRoute
  '/profile': typeof maincommonProfileRoute
  '/settings': typeof maincommonSettingsRoute
  '/attendance': typeof mainteacherAttendanceRoute
  '/classes': typeof mainteacherClassesRoute
  '/classroom': typeof mainteacherClassroomRoute
  '/reports': typeof mainteacherReportsRoute
  '/schools': typeof mainteacherSchoolsRoute
  '/students': typeof mainteacherStudentsRoute
  '/teachers': typeof mainteacherTeachersRoute
  '/lessons/$': typeof mainLessonsSplatRoute
  '/lessons': typeof mainLessonsIndexRoute
  '/lessons/$course/$unit/$lesson/$activity': typeof mainLessonsCourseUnitLessonActivityRoute
  '/lessons/$course/$unit/$lesson': typeof mainLessonsCourseUnitLessonIndexRoute
  '/lessons/$course/$unit/$lesson/embed/$id': typeof mainLessonsCourseUnitLessonEmbedIdRoute
  '/lessons/$course/$unit/$lesson/googleslide/$id': typeof mainLessonsCourseUnitLessonGoogleslideIdRoute
  '/lessons/$course/$unit/$lesson/pages/$id': typeof mainLessonsCourseUnitLessonPagesIdRoute
  '/lessons/$course/$unit/$lesson/youtube/$id': typeof mainLessonsCourseUnitLessonYoutubeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/$splat': typeof SplatRoute
  '/(main)/(teacher)': typeof mainteacherRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(main)/(common)/dashboard': typeof maincommonDashboardRoute
  '/(main)/(common)/profile': typeof maincommonProfileRoute
  '/(main)/(common)/settings': typeof maincommonSettingsRoute
  '/(main)/(teacher)/attendance': typeof mainteacherAttendanceRoute
  '/(main)/(teacher)/classes': typeof mainteacherClassesRoute
  '/(main)/(teacher)/classroom': typeof mainteacherClassroomRoute
  '/(main)/(teacher)/reports': typeof mainteacherReportsRoute
  '/(main)/(teacher)/schools': typeof mainteacherSchoolsRoute
  '/(main)/(teacher)/students': typeof mainteacherStudentsRoute
  '/(main)/(teacher)/teachers': typeof mainteacherTeachersRoute
  '/(main)/lessons/$': typeof mainLessonsSplatRoute
  '/(main)/lessons/': typeof mainLessonsIndexRoute
  '/(main)/lessons/$course/$unit/$lesson': typeof mainLessonsCourseUnitLessonRouteRouteWithChildren
  '/(main)/lessons/$course/$unit/$lesson/$activity': typeof mainLessonsCourseUnitLessonActivityRoute
  '/(main)/lessons/$course/$unit/$lesson/': typeof mainLessonsCourseUnitLessonIndexRoute
  '/(main)/lessons/$course/$unit/$lesson/embed/$id': typeof mainLessonsCourseUnitLessonEmbedIdRoute
  '/(main)/lessons/$course/$unit/$lesson/googleslide/$id': typeof mainLessonsCourseUnitLessonGoogleslideIdRoute
  '/(main)/lessons/$course/$unit/$lesson/pages/$id': typeof mainLessonsCourseUnitLessonPagesIdRoute
  '/(main)/lessons/$course/$unit/$lesson/youtube/$id': typeof mainLessonsCourseUnitLessonYoutubeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$splat'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/attendance'
    | '/classes'
    | '/classroom'
    | '/reports'
    | '/schools'
    | '/students'
    | '/teachers'
    | '/lessons/$'
    | '/lessons'
    | '/lessons/$course/$unit/$lesson'
    | '/lessons/$course/$unit/$lesson/$activity'
    | '/lessons/$course/$unit/$lesson/'
    | '/lessons/$course/$unit/$lesson/embed/$id'
    | '/lessons/$course/$unit/$lesson/googleslide/$id'
    | '/lessons/$course/$unit/$lesson/pages/$id'
    | '/lessons/$course/$unit/$lesson/youtube/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$splat'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/attendance'
    | '/classes'
    | '/classroom'
    | '/reports'
    | '/schools'
    | '/students'
    | '/teachers'
    | '/lessons/$'
    | '/lessons'
    | '/lessons/$course/$unit/$lesson/$activity'
    | '/lessons/$course/$unit/$lesson'
    | '/lessons/$course/$unit/$lesson/embed/$id'
    | '/lessons/$course/$unit/$lesson/googleslide/$id'
    | '/lessons/$course/$unit/$lesson/pages/$id'
    | '/lessons/$course/$unit/$lesson/youtube/$id'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/$splat'
    | '/(main)/(teacher)'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(main)/(common)/dashboard'
    | '/(main)/(common)/profile'
    | '/(main)/(common)/settings'
    | '/(main)/(teacher)/attendance'
    | '/(main)/(teacher)/classes'
    | '/(main)/(teacher)/classroom'
    | '/(main)/(teacher)/reports'
    | '/(main)/(teacher)/schools'
    | '/(main)/(teacher)/students'
    | '/(main)/(teacher)/teachers'
    | '/(main)/lessons/$'
    | '/(main)/lessons/'
    | '/(main)/lessons/$course/$unit/$lesson'
    | '/(main)/lessons/$course/$unit/$lesson/$activity'
    | '/(main)/lessons/$course/$unit/$lesson/'
    | '/(main)/lessons/$course/$unit/$lesson/embed/$id'
    | '/(main)/lessons/$course/$unit/$lesson/googleslide/$id'
    | '/(main)/lessons/$course/$unit/$lesson/pages/$id'
    | '/(main)/lessons/$course/$unit/$lesson/youtube/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$splat': {
      id: '/$splat'
      path: '/$splat'
      fullPath: '/$splat'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/(teacher)': {
      id: '/(main)/(teacher)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainteacherRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/lessons/': {
      id: '/(main)/lessons/'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof mainLessonsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/lessons/$': {
      id: '/(main)/lessons/$'
      path: '/lessons/$'
      fullPath: '/lessons/$'
      preLoaderRoute: typeof mainLessonsSplatRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(teacher)/teachers': {
      id: '/(main)/(teacher)/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof mainteacherTeachersRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(teacher)/students': {
      id: '/(main)/(teacher)/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof mainteacherStudentsRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(teacher)/schools': {
      id: '/(main)/(teacher)/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof mainteacherSchoolsRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(teacher)/reports': {
      id: '/(main)/(teacher)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof mainteacherReportsRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(teacher)/classroom': {
      id: '/(main)/(teacher)/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof mainteacherClassroomRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(teacher)/classes': {
      id: '/(main)/(teacher)/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof mainteacherClassesRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(teacher)/attendance': {
      id: '/(main)/(teacher)/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof mainteacherAttendanceRouteImport
      parentRoute: typeof mainteacherRouteRoute
    }
    '/(main)/(common)/settings': {
      id: '/(main)/(common)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof maincommonSettingsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(common)/profile': {
      id: '/(main)/(common)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof maincommonProfileRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/(common)/dashboard': {
      id: '/(main)/(common)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof maincommonDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson': {
      id: '/(main)/lessons/$course/$unit/$lesson'
      path: '/lessons/$course/$unit/$lesson'
      fullPath: '/lessons/$course/$unit/$lesson'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson/': {
      id: '/(main)/lessons/$course/$unit/$lesson/'
      path: '/'
      fullPath: '/lessons/$course/$unit/$lesson/'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonIndexRouteImport
      parentRoute: typeof mainLessonsCourseUnitLessonRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson/$activity': {
      id: '/(main)/lessons/$course/$unit/$lesson/$activity'
      path: '/$activity'
      fullPath: '/lessons/$course/$unit/$lesson/$activity'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonActivityRouteImport
      parentRoute: typeof mainLessonsCourseUnitLessonRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson/youtube/$id': {
      id: '/(main)/lessons/$course/$unit/$lesson/youtube/$id'
      path: '/youtube/$id'
      fullPath: '/lessons/$course/$unit/$lesson/youtube/$id'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonYoutubeIdRouteImport
      parentRoute: typeof mainLessonsCourseUnitLessonRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson/pages/$id': {
      id: '/(main)/lessons/$course/$unit/$lesson/pages/$id'
      path: '/pages/$id'
      fullPath: '/lessons/$course/$unit/$lesson/pages/$id'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonPagesIdRouteImport
      parentRoute: typeof mainLessonsCourseUnitLessonRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson/googleslide/$id': {
      id: '/(main)/lessons/$course/$unit/$lesson/googleslide/$id'
      path: '/googleslide/$id'
      fullPath: '/lessons/$course/$unit/$lesson/googleslide/$id'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonGoogleslideIdRouteImport
      parentRoute: typeof mainLessonsCourseUnitLessonRouteRoute
    }
    '/(main)/lessons/$course/$unit/$lesson/embed/$id': {
      id: '/(main)/lessons/$course/$unit/$lesson/embed/$id'
      path: '/embed/$id'
      fullPath: '/lessons/$course/$unit/$lesson/embed/$id'
      preLoaderRoute: typeof mainLessonsCourseUnitLessonEmbedIdRouteImport
      parentRoute: typeof mainLessonsCourseUnitLessonRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainteacherRouteRouteChildren {
  mainteacherAttendanceRoute: typeof mainteacherAttendanceRoute
  mainteacherClassesRoute: typeof mainteacherClassesRoute
  mainteacherClassroomRoute: typeof mainteacherClassroomRoute
  mainteacherReportsRoute: typeof mainteacherReportsRoute
  mainteacherSchoolsRoute: typeof mainteacherSchoolsRoute
  mainteacherStudentsRoute: typeof mainteacherStudentsRoute
  mainteacherTeachersRoute: typeof mainteacherTeachersRoute
}

const mainteacherRouteRouteChildren: mainteacherRouteRouteChildren = {
  mainteacherAttendanceRoute: mainteacherAttendanceRoute,
  mainteacherClassesRoute: mainteacherClassesRoute,
  mainteacherClassroomRoute: mainteacherClassroomRoute,
  mainteacherReportsRoute: mainteacherReportsRoute,
  mainteacherSchoolsRoute: mainteacherSchoolsRoute,
  mainteacherStudentsRoute: mainteacherStudentsRoute,
  mainteacherTeachersRoute: mainteacherTeachersRoute,
}

const mainteacherRouteRouteWithChildren =
  mainteacherRouteRoute._addFileChildren(mainteacherRouteRouteChildren)

interface mainLessonsCourseUnitLessonRouteRouteChildren {
  mainLessonsCourseUnitLessonActivityRoute: typeof mainLessonsCourseUnitLessonActivityRoute
  mainLessonsCourseUnitLessonIndexRoute: typeof mainLessonsCourseUnitLessonIndexRoute
  mainLessonsCourseUnitLessonEmbedIdRoute: typeof mainLessonsCourseUnitLessonEmbedIdRoute
  mainLessonsCourseUnitLessonGoogleslideIdRoute: typeof mainLessonsCourseUnitLessonGoogleslideIdRoute
  mainLessonsCourseUnitLessonPagesIdRoute: typeof mainLessonsCourseUnitLessonPagesIdRoute
  mainLessonsCourseUnitLessonYoutubeIdRoute: typeof mainLessonsCourseUnitLessonYoutubeIdRoute
}

const mainLessonsCourseUnitLessonRouteRouteChildren: mainLessonsCourseUnitLessonRouteRouteChildren =
  {
    mainLessonsCourseUnitLessonActivityRoute:
      mainLessonsCourseUnitLessonActivityRoute,
    mainLessonsCourseUnitLessonIndexRoute:
      mainLessonsCourseUnitLessonIndexRoute,
    mainLessonsCourseUnitLessonEmbedIdRoute:
      mainLessonsCourseUnitLessonEmbedIdRoute,
    mainLessonsCourseUnitLessonGoogleslideIdRoute:
      mainLessonsCourseUnitLessonGoogleslideIdRoute,
    mainLessonsCourseUnitLessonPagesIdRoute:
      mainLessonsCourseUnitLessonPagesIdRoute,
    mainLessonsCourseUnitLessonYoutubeIdRoute:
      mainLessonsCourseUnitLessonYoutubeIdRoute,
  }

const mainLessonsCourseUnitLessonRouteRouteWithChildren =
  mainLessonsCourseUnitLessonRouteRoute._addFileChildren(
    mainLessonsCourseUnitLessonRouteRouteChildren,
  )

interface mainRouteRouteChildren {
  mainteacherRouteRoute: typeof mainteacherRouteRouteWithChildren
  maincommonDashboardRoute: typeof maincommonDashboardRoute
  maincommonProfileRoute: typeof maincommonProfileRoute
  maincommonSettingsRoute: typeof maincommonSettingsRoute
  mainLessonsSplatRoute: typeof mainLessonsSplatRoute
  mainLessonsIndexRoute: typeof mainLessonsIndexRoute
  mainLessonsCourseUnitLessonRouteRoute: typeof mainLessonsCourseUnitLessonRouteRouteWithChildren
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainteacherRouteRoute: mainteacherRouteRouteWithChildren,
  maincommonDashboardRoute: maincommonDashboardRoute,
  maincommonProfileRoute: maincommonProfileRoute,
  maincommonSettingsRoute: maincommonSettingsRoute,
  mainLessonsSplatRoute: mainLessonsSplatRoute,
  mainLessonsIndexRoute: mainLessonsIndexRoute,
  mainLessonsCourseUnitLessonRouteRoute:
    mainLessonsCourseUnitLessonRouteRouteWithChildren,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
